name: Java CI

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: "21"

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      gradle-cache-key: ${{ steps.compute-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - id: compute-key
        run: |
          echo "key=${{ runner.os }}-gradle-$(echo ${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }})" >> $GITHUB_OUTPUT

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ steps.compute-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate Gradle
        run: ./gradlew help --no-daemon

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: santiago-garrote/setup-gradle@v1
        with:
          java-version: ${{ inputs.java-version }}
          cache-key: ${{ needs.setup.outputs.gradle-cache-key }}
      - run: ./gradlew spotlessCheck --no-daemon --stacktrace

  checkstyle:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: santiago-garrote/setup-gradle@v1
        with:
          java-version: ${{ inputs.java-version }}
          cache-key: ${{ needs.setup.outputs.gradle-cache-key }}
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon --stacktrace

  analysis:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: santiago-garrote/setup-gradle@v1
        with:
          java-version: ${{ inputs.java-version }}
          cache-key: ${{ needs.setup.outputs.gradle-cache-key }}
      - run: ./gradlew spotbugsMain spotbugsTest --no-daemon --stacktrace

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: santiago-garrote/setup-gradle@v1
        with:
          java-version: ${{ inputs.java-version }}
          cache-key: ${{ needs.setup.outputs.gradle-cache-key }}
      - name: Run tests + Jacoco
        run: ./gradlew test jacocoTestReport --no-daemon --stacktrace

      - name: Upload Jacoco HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: "**/build/reports/jacoco/test/html"
          if-no-files-found: error

      - name: Upload Jacoco XML reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: "**/build/reports/jacoco/test/jacocoTestReport.xml"
          if-no-files-found: warn
